### ISSUE TITLE
Updates from fluvio 0.10.10

### ISSUE THREAD

**Issue by morenol** [infinyon/fluvio-website#576]
## Todos

- [x] https://github.com/infinyon/fluvio-website/issues/577
- [x] https://github.com/infinyon/fluvio-website/issues/581
- [x] Update connector references
- [x] Update cdk deploy shutdown https://github.com/infinyon/fluvio-website/pull/578

**Comment by tjtelan** [comment]
Last todo completed - https://github.com/infinyon/fluvio-website/pull/585
